#define BEATS_Kick    36
#define BEATS_Snare   38
#define BEATS_LoTom   43
#define BEATS_HiTom   50
#define BEATS_ClosHat 42
#define BEATS_OpenHat 46
#define BEATS_Clap    39
#define BEATS_Claves  75
#define BEATS_Agogo   67
#define BEATS_Crash   49
